name: todo_app
description:
publish_to:

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6

  iconsax: ^0.0.8

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  #  Utility Package
  http: ^1.2.0
  intl: ^0.19.0
  lottie: ^2.7.0
  logger: ^2.1.0
  shimmer: ^3.0.0
  image_picker: ^1.0.7
  connectivity_plus: ^5.0.1
  url_launcher: ^6.2.5
  flutter_native_splash: ^2.3.11
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1

  #  Product Specific
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^3.1.0
  awesome_notifications: ^0.9.3+1


  #  Firebase
  firebase_core: ^2.27.2
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.16.0
  google_sign_in: ^6.2.1
  firebase_storage: ^11.7.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/
    - assets/images/on_boarding_images/
    - assets/icons/categories/
    - assets/images/banners/
    - assets/images/product_image/
    - assets/images/user/
    - assets/images/reviews/
    - assets/icons/payment_method/
    - assets/animation/loading_animation/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
        #          width: 300
        - asset: assets/fonts/Poppins-Regular.ttf
        #          width: 400
        - asset: assets/fonts/Poppins-Italic.ttf
        #          width: Italic
        - asset: assets/fonts/Poppins-Medium.ttf
        #          width: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
        #          width: 500
        #          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
        #          width: 600
        - asset: assets/fonts/Poppins-Bold.ttf
#          width: 800