// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiJh23ZDuk-LFkca0viQ_FJd2m13gak84',
    appId: '1:563263191246:web:dfdaa2567db1b5ae7db89f',
    messagingSenderId: '563263191246',
    projectId: 'todo-app-5c47b',
    authDomain: 'todo-app-5c47b.firebaseapp.com',
    storageBucket: 'todo-app-5c47b.appspot.com',
    measurementId: 'G-GG76H3M8X8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeDc6uqp_mbCVZ_QkP3YlDPio8fZIFukY',
    appId: '1:563263191246:android:da5855ccc2ba71727db89f',
    messagingSenderId: '563263191246',
    projectId: 'todo-app-5c47b',
    storageBucket: 'todo-app-5c47b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOl7Y-npubnXWdQme6opd5E3IPxTkbySU',
    appId: '1:563263191246:ios:ba616b60e648fd8d7db89f',
    messagingSenderId: '563263191246',
    projectId: 'todo-app-5c47b',
    storageBucket: 'todo-app-5c47b.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOl7Y-npubnXWdQme6opd5E3IPxTkbySU',
    appId: '1:563263191246:ios:ba616b60e648fd8d7db89f',
    messagingSenderId: '563263191246',
    projectId: 'todo-app-5c47b',
    storageBucket: 'todo-app-5c47b.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiJh23ZDuk-LFkca0viQ_FJd2m13gak84',
    appId: '1:563263191246:web:cc1fc08744e539677db89f',
    messagingSenderId: '563263191246',
    projectId: 'todo-app-5c47b',
    authDomain: 'todo-app-5c47b.firebaseapp.com',
    storageBucket: 'todo-app-5c47b.appspot.com',
    measurementId: 'G-5S4FJR47MY',
  );
}
